let temp = [ { day: '2017-05-08',
  symbol: { number: '800', name: 'sky is clear', var: '01n' },
  precipitation: {},
  windDirection: { deg: '36', code: 'NE', name: 'NorthEast' },
  windSpeed: { mps: '3.63', name: 'Gentle Breeze' },
  temperature:
   { day: '8.09',
     min: '5.11',
     max: '8.09',
     night: '5.11',
     eve: '8.09',
     morn: '8.09' },
  pressure: { unit: 'hPa', value: '1033.15' },
  humidity: { value: '65', unit: '%' },
  clouds: { value: 'clear sky', all: '0', unit: '%' } },
{ day: '2017-05-09',
  symbol: { number: '801', name: 'few clouds', var: '02d' },
  precipitation: {},
  windDirection: { deg: '49', code: 'NE', name: 'NorthEast' },
  windSpeed: { mps: '1.76', name: 'Light breeze' },
  temperature:
   { day: '12.91',
     min: '4.36',
     max: '14.38',
     night: '6.63',
     eve: '14.01',
     morn: '4.36' },
  pressure: { unit: 'hPa', value: '1028.66' },
  humidity: { value: '71', unit: '%' },
  clouds: { value: 'few clouds', all: '24', unit: '%' } },
{ day: '2017-05-10',
  symbol: { number: '800', name: 'sky is clear', var: '01d' },
  precipitation: {},
  windDirection: { deg: '109', code: 'ESE', name: 'East-southeast' },
  windSpeed: { mps: '2.66', name: 'Light breeze' },
  temperature:
   { day: '15.04',
     min: '5.62',
     max: '16.19',
     night: '8.15',
     eve: '14.57',
     morn: '5.62' },
  pressure: { unit: 'hPa', value: '1015.53' },
  humidity: { value: '60', unit: '%' },
  clouds: { value: 'clear sky', all: '0', unit: '%' } },
{ day: '2017-05-11',
  symbol: { number: '804', name: 'overcast clouds', var: '04d' },
  precipitation: {},
  windDirection: { deg: '91', code: 'E', name: 'East' },
  windSpeed: { mps: '6.65', name: 'Moderate breeze' },
  temperature:
   { day: '13.81',
     min: '10.08',
     max: '16.86',
     night: '13.75',
     eve: '16.86',
     morn: '10.08' },
  pressure: { unit: 'hPa', value: '1004.63' },
  humidity: { value: '62', unit: '%' },
  clouds: { value: 'overcast clouds', all: '88', unit: '%' } },
{ day: '2017-05-12',
  symbol: { number: '501', name: 'moderate rain', var: '10d' },
  precipitation: { value: '4.39', type: 'rain' },
  windDirection: { deg: '89', code: 'E', name: 'East' },
  windSpeed: { mps: '4.74', name: 'Gentle Breeze' },
  temperature:
   { day: '19.02',
     min: '12.54',
     max: '19.66',
     night: '13.33',
     eve: '19.66',
     morn: '12.54' },
  pressure: { unit: 'hPa', value: '1005.95' },
  humidity: { value: '0', unit: '%' },
  clouds: { value: 'broken clouds', all: '62', unit: '%' } },
{ day: '2017-05-13',
  symbol: { number: '501', name: 'moderate rain', var: '10d' },
  precipitation: { value: '9.13', type: 'rain' },
  windDirection: { deg: '244', code: 'WSW', name: 'West-southwest' },
  windSpeed: { mps: '2.53', name: 'Light breeze' },
  temperature:
   { day: '19.74',
     min: '12.61',
     max: '19.74',
     night: '13.85',
     eve: '17.58',
     morn: '12.61' },
  pressure: { unit: 'hPa', value: '1008.83' },
  humidity: { value: '0', unit: '%' },
  clouds: { value: 'scattered clouds', all: '37', unit: '%' } },
{ day: '2017-05-14',
  symbol: { number: '500', name: 'light rain', var: '10d' },
  precipitation: { value: '1.12', type: 'rain' },
  windDirection: { deg: '225', code: 'SW', name: 'Southwest' },
  windSpeed: { mps: '4.94', name: 'Gentle Breeze' },
  temperature:
   { day: '17.16',
     min: '11.24',
     max: '17.16',
     night: '11.24',
     eve: '16.87',
     morn: '11.83' },
  pressure: { unit: 'hPa', value: '1019.21' },
  humidity: { value: '0', unit: '%' },
  clouds: { value: 'few clouds', all: '19', unit: '%' } } ]


module.exports = temp